### ISSUE TITLE
Listal export not saving anything/Letterboxd import ends in error

### ISSUE THREAD

**Issue by VierasTalo** [StegSchreck/RatS#45]
Hi. I'm running this on a VM using Ubuntu. That might have something to do with the issue. Anyhow. I can't seem to get the Listal->Letterboxd-conversion to work. As the log below notes the export doesn't save anything to the JSON-file though it seems to log in just fine, and the import ends in _"raise exception_class(message, screen, stacktrace) selenium.common.exceptions.ElementNotInteractableException: Message: Element <input id="upload-imdb-import" name="file" type="file"> is not reachable by **keyboard**_

EDIT: OK Now I did the -x using the command and it definitely scrolls through all the movies correctly, then logs in to Letterboxd and does nothing. As it doesn't actually save the movies it scrolls through.

I filled out all the details below to my best ability.

## System
* Version: Latest as of 7/2/2018
* Platform: Ubuntu 16.04.03 X64
* Firefox version: Firefox 58.0.1
* Geckdrover version: 0.19.1
* Python version: 3.5.2
* PIP version: PIP 3 is 8.1.1 PIP is 9.0.1
* Running in a virtualenv?: Yes
* Running in Docker?: No
* Executed command: python3 transfer_ratings.py --source listal --destination letterboxd

## Stacktrace
```
miikka@miikka-VirtualBox:~/RatS$ python3 transfer_ratings.py --source listal --destination letterboxd
===== Listal: Parsing 54 pages with 3188 movies in total
 
===== Listal: saved 0 parsed movies to /home/miikka/RatS/RatS/exports/20180207174432_Listal.json
===== Letterboxd: posting 0 movies
===== saving movies to CSV
Traceback (most recent call last):
  File "transfer_ratings.py", line 158, in <module>
    main()
  File "transfer_ratings.py", line 65, in main
    execute(args)
  File "transfer_ratings.py", line 124, in execute
    insert_movie_ratings(inserter, movies, type(parser.site).__name__)
  File "transfer_ratings.py", line 154, in insert_movie_ratings
    inserter.insert(movies, source)
  File "/home/miikka/RatS/RatS/letterboxd/letterboxd_ratings_inserter.py", line 33, in insert
    self.upload_csv_file(len(movies))
  File "/home/miikka/RatS/RatS/letterboxd/letterboxd_ratings_inserter.py", line 50, in upload_csv_file
    self.site.browser.find_element_by_id('upload-imdb-import').send_keys(os.path.join(filename))
  File "/home/miikka/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 479, in send_keys
    'value': keys_to_typing(value)})
  File "/home/miikka/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "/home/miikka/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/home/miikka/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: Element <input id="upload-imdb-import" name="file" type="file"> is not reachable by keyboard
```

**Comment by StegSchreck** [comment]
Hey @VierasTalo. 

Ok, I see multiple issues here.

1. For some weird reason (which I do not understand yet), the parser was not saving any data into the json file. This is most certainly a problem with the parsing itself. At least the number of pages and movies to be parsed seem to be valid. Between that line and the line `... saved 0 movies to ...`, there should be a progress bar indicating the progress of the parsing including the remaining time, e.g.
`Listal 721/1511 0:55:59 [##########################----------------------------] 47.7%`
Btw. how long was the runtime of the script in your case?
2. I noticed while testing locally, that the Listal parser is not fault-tolerant if the detail page of a movie is missing the release year
3. The inserter is trying to do something, despite there is no movie to be inserted
4. The CSV file could not be uploaded to Letterboxd, because the input field for the file on the upload page is not ready to be interacted with.

I already made fixes for no. 2, no. 3. and no. 4. Still, the main issue here is no. 1.

I did try to parse from Listal in my natively installed Manjaro Linux and inside an Ubuntu 16:04 Docker container, but both were parsing the data correctly. I did see a progress bar in the console and the resulting output JSON was filled with valid data. So, I cannot reproduce the same behavior that you are experiencing, which unfortunately reduces my ability to fix the problem because I don't see the actual problem. :/

I assume the following files to be basically empty. Can you confirm this?
- `/home/miikka/RatS/RatS/exports/{timestamp}_Listal.json`
- `/home/miikka/RatS/RatS/exports/{timestamp}_converted_for_Letterboxed.csv`

Could you please provide the Geckodriver logfile, which should be located at `/home/miikka/RatS/{timestamp}_geckodriver.log`. I hope this includes some insights about why it didn't parse the data properly.

In the meantime, did you try if the script runs properly for you if you use the provided [Docker image](https://hub.docker.com/r/stegschreck/rats/)? Alternatively, you could use the `-v` or `-vv` or `-vvv` in order to increase the level of verbosity for the parser, which also might give some hints about the underlying issue.

Sorry for writing such a long text without providing a solution for the problem you are experiencing.

**Comment by VierasTalo** [comment]
I re-downloaded the latest version just now so now I get the error message that there are no files to be inserted.

> there should be a progress bar indicating the progress of the parsing including the remaining time, e.g.
I don't actually see any progress bar. I just get the Listal: Parsing X pages with Y movies in total, then it just blanks out until it says Listal: Saved 0 parsed movies to *path*

> Btw. how long was the runtime of the script in your case?
I just timed this, it was around 2 minutes 20 seconds from pressing Enter to the new error message popping up.

> I assume the following files to be basically empty. Can you confirm this?
The timestamp_Listal.json-files are empty. With the new version there are no .csv-files for Letterboxd.

> Could you please provide the Geckodriver logfile
I've attached it to this post.
[20180208011009_geckodriver.log](https://github.com/StegSchreck/RatS/files/1705100/20180208011009_geckodriver.log)

> In the meantime, did you try if the script runs properly for you if you use the provided Docker image? 
I'm afraid I have zero experience with Docker images. I can read up on the subject, but as a not-very-experienced user, it'll take a while for me to get the hang of it. I'll give it a go during this week.

> Alternatively, you could use the -v or -vv or -vvv in order to increase the level of verbosity for the parser, which also might give some hints about the underlying issue.
I've attempted this, however it doesn't seem to make any difference to the end result.

**Comment by StegSchreck** [comment]
Hey @VierasTalo,
sorry that I didn't check back in a long tíme now. But I'm currently quite busy at work with migration of our infrastructure and preparing conference talks. 
How is your current status with this issue? Did you try the docker solution?
If it still doesn't work for you, please let me know, so I will have a look asap.
Best regards
